### ISSUE TITLE
Change to behaviour of PRT-code with units input

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#222]
Hi,

Our newest merge from master to abacus broke old behaviour (like three months old that is) in an interesting way and we see that same problem in master. The situation is that there exists plenty of old units using questions that are were being updated to use the new units input by just switching the input type and leaving the old answer tests in place as they did the same things as the new units answer tests, but suddenly switching to units input breaks the old code by changing the behaviour of `coeff` in some mystical way. 

Obviously the behaviour of the PRT logic should not depend on the type of input used to input the value to it should it? Now things that work with Algebraic input do not work with the Units input which is odd as previously they did, see the attached minimal case which ignores the parts that would do the unit conversions happening in the current answer test.
[test units-input vs old school units.xml.gz](https://github.com/maths/moodle-qtype_stack/files/342979/test.units-input.vs.old.school.units.xml.gz)

**Comment by aharjula** [comment]
Basically, the behaviour of the `coeff`-function breaks even when the value of the input seems the same, something somewhere leaks something that affects the feedback-variables, but what is it?

**Comment by aharjula** [comment]
Maxima version was 5.36.1 (CLISP) should it be relevant.

**Comment by sangwinc** [comment]
Matti,

Please let me apologise profusely for not fully documenting an important change in the behaviour of the input type.  I really am sorry about this.  The problem originates here:

https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/stackunits.mac#L192

and I've pushed better docs: 
https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Authoring/Units.md

I sincerely believe having the input type split the student's answer and return an inert function is a serious improvement.  The fact you had so much trouble tracking down where coeff goes wrong was very similar to a problem I had.  This is why I changed the behaviour so teachers need not worry how to split a student's answer into the numerical part and units part.  But, this will create work for you in changing your questions.

There is also the function "stack_units_split" which will return a *list*.
stack_units_split
I did consider changing this to return a "stackunits" function, not a list.

Sorry again.....

**Comment by aharjula** [comment]
Ok. So I'll have to explain to our physics people that the new thing they were happy with has changed a bit. Well this can almost be fixed with a search and replace on the feedback vars to change from the old `coeff` to this new `first(args(ans1))` form where the units are lumped together. I am wrong when I assume that `stack_unit_si_to_si_base` works with these new inert functions or does it already handle them? Argh I am wrong if `ans1 = 10*km` then `first(args(stack_unit_si_to_si_base(ans1)))` is 10000 but when `ans1 = stackunits(10,km)` gues what it is...

**Comment by aharjula** [comment]
Ok so that `stack_unit_si_to_si_base` is an important issue as we have 555 PRTs that use it and will need to be rewritten 552 of them requiring that `coeff` bit to be fixed to this new one (especially as the new one is not logically equivalent it does not contain the logic of checking for the same unit). Basically, we could make someone click through all of those PRTs stripping out some nodes and simply switching to the Units answer test but then they would need to read through the feedback variables code checking for special cases (and there are many) not covered by that answer test and map those out after throwing out all those extra nodes previously used for the written out version of that Units answer test, but they just went through the questions and switched all the inputs to that Units input so it would be sensible to minimise the amount of work they have to do and if they need to start handling the inconsistent behaviour of that key function they have used for many years they will not be happy.

Ahh, a small change causing plenty of work... almost considering another units input type that does not do this for the legacy materials.

**Comment by sangwinc** [comment]
Mea Cupla Matti,

Perhaps we should have a hard look at the units and propose some way of moving forward before we rush to fix this?  (I will move quickly however....)

We could add an option to the input type to replace stackunits with "*".  

E.g. try
  ans1:stackunits(10,m/s);
  subst("*",stackunits,ans1);
So, we could globally add an option to your inputs (in the DB) and have the option make the substitution.  

This would (1) retain the old behaviour, (2) keep the new design, (3) not fork or have "old units" legacy.  

What do you think about the new behaviour?

What do you think about the proposed fix?

Chris

**Comment by aharjula** [comment]
That option to the input type would be the simplest fix for the problem and would indeed solve the situation without we having to plug that code to each and every feedback-variables field. So and option to the input type to output raw expressions in the legal style instead of this new one that uses different semantics and has better typesetting?

Well the new behaviour is good for people that have not gotten used to the old way, only thing I find awkward is the fact that one needs to call two functions (`first`/`second` and `args`) to get the parts out of the object, but one can't have everything. So nothing against it but backwards compatibility issues were quite large...

As to other broken things, I need this to return the same value for both forms of input `first(args(stack_unit_si_to_si_base(ans1)))` so do modify that function to be able to handle both forms in a consistent way. The issue there is that while your `stackunits` construct claims to have the numbers in the first part and the units in the second calling that very commonly used function can result in an object with numbers in both parts... maybe we are lucky that it has not broken the answer test or maybe it has and there is no unit test that notices it or maybe you made it so that that does not happen.

**Comment by sangwinc** [comment]
Matti,

I have written some proposed code here:
https://github.com/maths/moodle-qtype_stack/tree/i222

I have some concerns that this code will subtly change the student's expression, e.g. 5*(m/s) might be transformed to (5*m)/s.  This may well break your coeff code in any case....  Please can you let me know what happens with this before we merge this back into master?

In addition, we can very easily add two new functions, such as the following:

```
stack_units_units(ex);
stack_units_num(ex);
```
which return the "units part" and "numerical part".  Would this be helpful?  It would certainly solve the problem once and for all.  I probably should have done this originally, and then your authors would never have been messing around with "coeff" in the first place....

Yes, we should change stack_unit_si_to_si_base as well.  This is why it might be a good moment to pause and consider whether you agree with the stackunits(num,units) approach here?

**Comment by aharjula** [comment]
As to my understanding the `coeff` has no problem with `(5m)/s` vs. `5(m/s)` as long as `simp:true` so wouldn't worry about that.

As to this inert function thing, how do you expect people that ask for some dimensions like length and width to react in their feedback code when they multiply those input variables and get something else than an evaluated area as the result? Have you considered fleshing out the calculation rules for these inert functions so that at least the simplest operations could be done without resorting to extracting arguments from the functions? Seems like a lot of effort is now required for the simplest of tasks...

A while ago I had an issue with the behaviour of integrals that had constant multipliers inside them and the way that they got rendered i.e. I did not like the way the constant was placed in front of the integral sign instead of inside it. To fix that problem I came across the `outtative` property of functions and started to strip that property from the `integral` function, could there exist a similar one for expressions so that we could use here... It could be used to implement `stackunits*stackunits` for the numerical part, well probably not but there is such a thing as multiouttative...

Note that our authors have been messing with `coeff` with units from the very beginning many years before you touched any units code, this is that kind of a legacy issue.

Maybe `stack_unit_si_to_si_base` could return `stackunits` when it receives them and these legacy expressions when it get such and thus would not cause the input to change its type, would ease peoples lives as it is the function they most likely will still need to call if they wish to do something in the feedback-variables. The answer-test will never cover everything nor should we ever try to cover everything with it.

One fun little issue, I can't input `10*m+10*cm` into these Units inputs, but maybe that was lost already when you made the first version of Units input, probably not needed...

**Comment by aharjula** [comment]
Chris, that `mul` option seems to work when merged to abacus and used with the questions that brought up this issue. But now that I have thought about this for quite some time the benefit for the rendering logic that this `stackunits` brings is not big enough to offset the inconvenience (the separation of units from numbers has been possible before and could even then be done with functions so not a new feature offsetting the inconvenience) that it causes for people that expect that they can do algebraic operations with the answers and there are those people that have worked with the original units system from the days of STACK 1.X and gotten used to the fact that you can push raw inputs through pretty much every operation one can think of and expect to get a sensible results as long as they call `stack_unit_si_to_si_base` either before they push those values to the operations or after all the operations to coalesce the results.

I am not saying that there are a large number of questions that would actually do calculations with the inputs instead of just comparing them to the teachers answer but they do exist and we have supported them from the very beginning of that units system so dropping that feature seems like a step back and not a small step...

**Comment by aharjula** [comment]
Hi,

Anything new about this? Have the other physics people said anything?

**Comment by sangwinc** [comment]
Matti, thank you for prompting me on this again.  I'm just (yesterday) back from ICME, which had a lot of very interested colleagues who are already using STACK.

I plan to work on, and I hope resolve, this issue during the week.  

Do you have a concrete suggestion?

Chris

**Comment by aharjula** [comment]
Well my thinking is still as follows:

1. `stack_unit_si_to_si_base` needs to work for both the old form expressions and the new `stackunits` idealy so that if possible it returns the same format it was given. So not this `stack_unit_si_to_si_base(stackunits(10,km)) = stackunits(10,1000*m)` that should return `stackunits(10000,m)` and if I mixed something like `5*km` to that expression the return value should not contain any `stackunits`.
2. `mul`is ok and I'll need to merge it to abacus soon to get ready for teaching starting in early September.
3. Would be nice if basic mathematical operations were defined for `stackunits` i.e. `stackunits(5,m)*stackunits(2,cm) = stackunits(10,m*cm)`
4. In some old, probably newer used, use case we had an physic exercise that asked the student to write the answer so that it consisted of the sum of forces applied as an expression where the different forces were different terms and the evaluation could check for the missing terms term by term. So in theory that `10*m+10*cm` that does not work with the units input might be relevant, but that can still be done with algebraic input although the validation looks different.

So as long as you can get that first one working most things should work, the third one would also help but maybe we can consider that a lost feature although new users will probably want something similar at some point. The fourth is an edge case that can be ignored. From the technical side I would consider the third to be the hardest and the fourth probably would require stripping some of that `stackunits` logic from the system or changing it to apply term by term, although units might appear in the middle of deeper expressions so that would be hard...

Naturally, you could always just roll-back the `stackunits` to fix all the three first ones an probably even the fourth one.

**Comment by aharjula** [comment]
As to the first point try this question and tell me could the first point be related to the issue I have answering to the question in m/s? Or am I doing something else wrong with the units input or test?
[test units input kmh vs ms.xml.gz](https://github.com/maths/moodle-qtype_stack/files/396153/test.units.input.kmh.vs.ms.xml.gz)

**Comment by sangwinc** [comment]
Thanks Matti, I will try to look at this during this afternoon or tomorrow.  Lots of post ICME stuff came up, which is very exciting.  This issue is very important.

**Comment by sangwinc** [comment]
Matti,
Thanks for your comments and patience with this.  I've merged i222 into ATUnitsNum, and am now working in there to come up with a resolution to this.  
(1) is done:  stack_unit_si_to_si_base works for both the old form of expressions and the new stackunits and it returns the same format it was given.
(3) & (4) are done.  Addition will only work for expressions with the same units.  You will have to force conversion to base units for your example 10*m+10*cm.

```
stack_unit_si_to_si_base(stackunits(10,km));
stack_unit_si_to_si_base(10*km);
```

Thanks for being so patient about this.
Any further comments.  E.g. did I miss something?

**Comment by aharjula** [comment]
`column "syntaxattribute" does not exist` if we try to upgrade to the ATUnitsNum branch from master... obviously masters versions have passed the upgrade versions in that branch...

I still can't seem to answer `125/9*m/s` to that example I last attached, am I doing something wrong, has there been some new change? I.e. I thought you could pass exact values to NumSigFigs?

(4) maybe you did not understand what I meant, if I have a Units type inputs like that sample question that asks to input `50*km/h` or `125/9*m/s` and I try to input `20*km/h+30*km/h` (the prefixes of the units do not matter) it does not get though the input system as it can't find the units... Maybe if we can't turn the expression to a `stackunits()` we could just push it forward as an expression... but that would complicate peoples lives if they assume they are getting the packaged version as input.

(3) can we get `stackunits(1,km)*50/h = stackunits(50,km/h)` (probably not as then you would need to conditionally move the variables into the inert thing, unless of course you could add some tag to the units and write the rule to check for that tag), mixing the different notations is highly likely when the students answer hits the cas code written by the question author they probably have not wrapped every single value they have to that inert thing... also maybe `is(50*m=stackunits(50,m)) = true`

**Comment by aharjula** [comment]
Also was it so that ATUnitsNum is the branch with space implies multiplication? If so can I just take the `stackunits.mac` and live with that so that I do not need to merge that space thing with so short a testing time?

**Comment by sangwinc** [comment]
Thanks Matti,

(0) Re. 125/9*m/s, you can pass ATNumSgFigs floats or integers, but not
rational numbers.  I'm not sure what it means to give a rational number to
a certain number of significant figures!
https://github.com/maths/moodle-qtype_stack/blob/ATUnitsNum/stack/maxima/
stackmaxima.mac#L864

However, in the case of "units" we provably do want to test if numbers are
exact.  Do you have a specific proposal here?

(4) The example you give of 20*km/h+30*km/h is interesting.  Currently the
units input type rejects this as invalid as units are expected to be
exactly a number*units.  Perhaps we should reject sums with a more specific
message?

(5) stackunits(1,km)*50/h -> stackunits(50,km)/h.  How many simplification
rules should we add?

(6) I think that is(50*m=stackunits(50,m)) should be "false", but we should
add in something to ATAlgEquiv to make them considered to be equivalent.
The easy way to do this is remove all stackunits and replace them with
multiplication.  What do you think?

Chris

On Fri, Aug 5, 2016 at 7:39 AM, Matti Harjula <notifications@github.com>
wrote:
>
> Also was it so that ATUnitsNum is the branch with space implies
multiplication? If so can I just take the stackunits.mac and live with that
so that I do not need to merge that space thing with so short a testing
time?

**Comment by aharjula** [comment]
(0) Ahh, makes sense that the NumSigFigs heritage comes through, got confused with a quick conversion of an old question that allowed exact answers. Makes sense that rarely needed things like this would not need to exist in the basic test. And the major issue of not accepting `13.8*m/s` has now been fixed. So sorry for a pointless issue and lets forget this...

(4) Some sort of an message would make sense but how to identify the situation...

(5) Don't know how many rules we need but trying to minimise the complications of mixing the encapsulated input values with raw expressions that might exist on the code side would simplify the coding process.

(6) Just having an issue with things that are meant to represent the same not being equal in the logical sense. I understand perfectly that to get the pretty rendering the number-unit pairs need to have this kind of a wrapper but the amount of "normal" and "expected" functionality that got broken by this is quite large and everything that can be done to make these things work equivalently to the old expressions should be done.

`stack_units_units(ex)` and `stack_units_nums(ex)` that you mentioned could help here by working for both the encapsulated things and expressions. Also maybe we could also have one more that would mimic the old `coeff()` logic e.g. 'stack_units_mult(stackunits(5,kg/m),kg/m) = 5', 'stack_units_mult(stackunits(5,kg/m),kg) = 5/m', 'stack_units_mult(stack_units_si_to_si_base(2*W),1/s) = stack_units_si_to_si_base(2*J)' and importantly `stack_units_mult(stackunits(5,kg),m) = 0`. The `coeff` logic has the benefit of checking the unit at the same time it extracts the numeric value.

**Comment by aharjula** [comment]
Another fun little detail, ATUnits is now something else, there probably is an upgrade script that fixes old questions from ATUnits to ATUnitsSigFigs and from the strict variant... Atleast when you merge that ATUnitsNum branch to master there should be.

**Comment by sangwinc** [comment]
Matti,

Thanks for this last comment.  I've checked the code, see
https://github.com/maths/moodle-qtype_stack/blob/master/stack/answertest/controller.class.php#L176
The old questions will still have the answer test "ATUnits" which is now mapped onto a new Maxima function.  There is no need to "fix" old questions as the old behaviour is preserved, but thanks for making me check this!

**Comment by aharjula** [comment]
Ok. Sorry about that trying to merge these fixes without that space thing in our very limited time frame led to a situation where I did not notice that file at all... So yet another thing that is ok... Maybe I'll add those new test to the merge as well.

**Comment by aharjula** [comment]
Now for something really odd... 
![meters](https://cloud.githubusercontent.com/assets/980957/17697096/66ed2e12-63bb-11e6-95cc-3ce8e179a888.png)

So that example I had where I had the misunderstanding of exact values, now being run in a Moodle with plenty of other plugins. And something is now doing weird things as the first fraction there should display `km/h` values and for some reason it has turned that to "meters" and most surprisingly even managed to do the prefix conversion while doing that. What could have caused that to happen? It should look like this (being run with the same code on same Moodle version, but probably entirely different settings), surely there is nothing inside STACK that would cause that or is there?

![other moodle](https://cloud.githubusercontent.com/assets/980957/17697213/2066c6dc-63bc-11e6-87eb-692b1cda4e82.png)

**Comment by sangwinc** [comment]
Matti,
Would you like me to look at your "meter" problem?  Otherwise, can we close this issue?
Chris

**Comment by aharjula** [comment]
Nah. That meter issue was a mess with multiple different versions of units code living in the same maxima, nothing to do with you.
